name: CI (dev)

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/ci_dev.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      environment: development
  lint:
    uses: ./.github/workflows/lint.yaml
  unit-test:
    uses: ./.github/workflows/test-unit.yaml
  integration-test:
    uses: ./.github/workflows/test-integration.yaml
    secrets: inherit
    with:
      environment: development
