name: Integration Test

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIRE_API_KEY:
        required: true
      FIRE_AUTH_DOMAIN:
        required: true
      FIRE_PROJECT_ID:
        required: true
      FIRE_STORAGE_BUCKET:
        required: true
      FIRE_MESSAGING_SENDER_ID:
        required: true
      FIRE_APP_ID:
        required: true
      FIRE_MEASUREMENT_ID:
        required: true

jobs:
  integration:
    name: Integration Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: cache-node-modules
        uses: actions/cache@v3
        id: cache-node
        env:
          cache-name: cache-node
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-cache-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cache-node-
            ${{ runner.os }}-cache-
            ${{ runner.os }}-
      - name: Install node modules
        if: ${{ steps.cache-node.outputs.cache-hit != 'true' }}
        run: pnpm i
      - name: Integration Test
        run: pnpm run test --dir=integration
